### PR TITLE
Task 1

### PR DESCRIPTION
**Pull request by nafees492**

### CODE REVIEW

**Comment by nishkalprakash** [comment]
####Few things to improve:
- change interpolated gray scale (pleasing to view) to average gray scale (actual grey scale).
- dont use the master branch for your edits, use the branch you made `mtp-nafees-shaikh-22CS60R42`.
- Never ask the master branch (nishkalprakash:master) to pull your code,  I have made a branch for you and have changed the pull request to use that branch instead.

####After this get started on Milestone 2
Rest is fine.

**Comment by nafees492** [comment]
ok, I will remember and If I won't understand the last 2 point (part about
git), I will come to takshila and ask.

Thanks.

**Comment by nishkalprakash** [comment]
You dont have to come to tax,
you can just email or call.
we can have an online meet

**Comment by nafees492** [comment]
sure, then I will call if I want to ask anything.

**Comment by nafees492** [comment]
Actually I am confused a bit, whether my commit is happening in my
repository or the main , so if we can have a meet where I can get it
resolve.

**Comment by nishkalprakash** [comment]
Great Work on Milestone 1.

For Milestone 2 try to implement a class if you think it will make it easier.

**Pull request merged**
